name: SplatPlugin
main: com.silent_herbert.splatplugin.SplatPlugin
version: 1.5
api-version: 1.20
commands:
  team:
    description: Join a team
    usage: /team <color>
  giveweapon:
    description: get a weapon
    usage: /giveweapon <weapon>
  clearink:
    description: Clear all ink from the world
    usage: /clearink
