name: SplatPlugin
main: com.silent_herbert.splatplugin.SplatPlugin
version: 1.5
api-version: 1.20
commands:
  team:
    description: Join a team
    usage: /team <color>
  givesplatter:
    description: Get The Splatter weapon
    usage: /givesplatter
  clearink:
    description: Clear all ink from the world
    usage: /clearink
  givedebug:
    description: Get the Debug Splatter weapon
    usage: /givedebug
